# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    - id: clang-format
      name: clang-format
      entry: clang-format -i
      language: system
      types: [c, c++]
      files: \.(cpp|hpp|h)$

    - id: clang-tidy
      name: clang-tidy
      entry: clang-tidy
      language: system
      types: [c, c++]
      files: \.(cpp|hpp|h)$

-   repo: local
    hooks:
    - id: run-tests
      name: Run tests before push
      entry: ./scripts/run_tests.sh
      language: script
      stages: [pre-push]
